Question1:

- Ask the user to enter a temperature three times using input().
- Convert each input to float.
- Use a for loop to repeat the 3 inputs.
- For each input, use if-elif-else:
- If temperature < 15 → print "Cold"
- If 15 ≤ temperature < 25 → print "Warm"
- If temperature ≥ 25 → print "Hot"

In [25]:
temp1 = float(input("Enter First Temperature: "))
temp2 = float(input("Enter Second Temperature: "))
temp3 = float(input("Enter Third Temperature: "))

for i in range(1,4):
    temp = float(input("Enter First Temperature: "))
    if temp < 15:
        print("Cold")
    elif temp >= 15 and temp < 25:
        print("Warm")
    else:
        print("Hot")

    
#    if i == 1:
#     if temp1 < 15:
#         print("Cold")
#     elif temp1 >= 15 and temp1< 25:
#         print("Warm")
#     else:
#         print("Hot")
    
#    if i == 2:
#     if temp2 < 15:
#         print("Cold")
#     elif temp2 >= 15 and temp2< 25:
#         print("Warm")
#     else:
#         print("Hot")

#    if i == 3:
#     if temp3 < 15:
#         print("Cold")
#     elif temp3 >= 15 and temp3< 25:
#         print("Warm")
#     else:
#         print("Hot")


Cold
Cold
Cold


Question2:

- Ask the user to input a word (string).
- Use a for loop to go through the first 5 characters of the word (or fewer if the word is shorter).
- For each character, print:
- Its index and the character at that index.
- Use if-elif-else to check:
- If the character is a vowel → print "Vowel"
- If it's a consonant → print "Consonant"
- If it's not a letter → print "Other character"

In [18]:
print(type(temp1))

str_word = input("Enter any word: ")
len_word = len(str_word)

for i in range(len(str_word)):
   if i <= 5: 
    if str_word[i] in 'aeiouAEIOU':
        print(i,str_word[i],"Vowel")
    elif str_word[i] in 'bcdefghjklmnpqrstvwxyzBCCDFGHJKLMNPQRSTVWXYZ':
        print(i,str_word[i],"consonent")
    else:
        print(i,str_word[i],"Other CHaracter")
   else:
    print("Length of word is more than 5")
    break

# for j in str_word:
#     if j in 'aeiouAEIOU':
#         print(j,"Vowel")
#     elif j in 'bcdefghjklmnpqrstvwxyzBCCDFGHJKLMNPQRSTVWXYZ':
#         print(j,"consonent")
#     else:
#         print(j,"Other CHaracter")


<class 'float'>
0 a Vowel
1 l consonent
2 a Vowel
3 m consonent
4 g consonent
5 i Vowel
Length of word is more than 5


In [19]:
import numpy as np
list = [[1,2,3,4],
        [5,6,7,8], 
        [9,10,11,12]]
list_2 = [9,10,11,12]

slicing_numpy = np.array(list)
slicing_numpy[:,::-1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [5]:
import pandas as pd

df = pd.DataFrame([[10, 20, 30],
                   [40, 50, 60]],
                  columns=["A", "B", "C"])

In [22]:
row_1_col_1 = df.at[1,"A"]
row_1_col_1

40

In [23]:
row_2_col_3 = df.at[1,"C"]
row_2_col_3

60

In [26]:
slicing_1 = df.iloc[1]["C"]
slicing_1

60

In [ ]:

slicing_df = df.values[:,::-1]
slicing_df

array([[30, 20, 10],
       [60, 50, 40]], dtype=int64)

In [15]:
slicing_df = df.values[:, -3:]
slicing_df

array([[10, 20, 30],
       [40, 50, 60]], dtype=int64)

In [16]:
slicing_df = df.values[:, -3:][:, ::-1]
slicing_df


array([[30, 20, 10],
       [60, 50, 40]], dtype=int64)

In [29]:
df = pd.DataFrame({
    "A": [10, 20, 30, 40, 50],
    "B": [5, 15, 25, 35, 45]
})
df

A   B
0  10   5
1  20  15
2  30  25
3  40  35
4  50  45

In [ ]:
print(df.loc[3,"A"]) # label based
print(df.iloc[3,0]) # index based
print(df.at[3,"A"]) # single value

40
40
40
